  const jobs = [
  {
    company: "Deqode",
    type: "Full-Time",
    description:
      "In-depth understanding of OOP, microservices design patterns, domain driven design, data structures, algorithms, and concurrency.Experience building secure, distributed, scalable, high-performance, resilient systems.Proven track record in building products on big data systems such as Kafka. and Kinesis.Experience with Agile Development Methodologies and Test-Driven Development.Excellent communication and teamwork skills.Nice to have: Experience developing in JavaScript on NodeJS Payments domain expertise. ",
  },
  {
    company: "Deqode",
    type: "Full-Time",
    description:
      "The Development Lead software position exists to lead a remote team that will build and maintain publishing solutions.This includes developing systems and functions such as content delivery web sites, content loading, access control, reporting, analytics and other publishing-related tools and controls.ESSENTIAL JOB FUNCTIONS AND RESPONSIBILITIES:The job functions include, but are not limited to, the following:Supervising direct report developers which includes managing the developers, approving time off, hiring new team members and evaluating performanceLead a team of 3-7 people delivering technical projects in an Agile scrum processMore than 7 years of experience working on major software development projectsusing .NET Framework/Core, C# and SQL Server databasesStrong focus on meeting business needs through a detailed understanding of userrequirements and effective and accurate implementation of technical specificationsIn-depth knowledge and experience with object-oriented design conceptsIn-depth knowledge and experience of relational databases and SQL Server inparticularDevelop software that is of high quality, maintainable, reliable and able to modifiedby other developersUnderstands browser specific compatibility issuesActively contributes to the corporate knowledge baseAble to coach and mentor other engineersAble to prioritise and lead multiple projectsStrong Communication skillsGood architecture skillsQUALIFICATIONS AND EDUCATIONAny combination equivalent to, but not limited to, the following:Desirable but not required to have a 4 year technical degree from an accrediteduniversityRelevant Certifications are a plusMinimum of 7 years experience in applicable software development toolsetsMinimum of 2- 3 years as a Development lead or manager in a hands on roleExperience working in a telecommuting capacity and managing remote staffExperience working in the publishing industry is a plusLANGUAGE, ANALYTICAL SKILLS AND SPECIFICATIONSAny combination equivalent to, but not limited to, the following:Reading and interpreting requirements documentsMaintain confidentialityAbility to solve problems and address unique challengesAbility to communicate clearly and effectively, both oral and writtenMaintain professionalism at all timesBe reasonable, collegial and have a willingness to adaptBe creative and be well organizedBe self-motivated and have the ability to multi-taskBe able to be interrupted and to work on multiple concurrent projectsBe willing and able to meet with customers and to maintain a productive relationshipBe able to handle stress under the duress of tight schedulesAbility to work well with other team members, including project managers, otherdevelopers and testersDesire to help others as neededAbility to work independentlyAbility to follow internal coding standards and architectural practicesAbility to lead internal code reviewsAbility to architect systems based on discussions with product managers and businessanalystsPHYSICAL DEMANDSAny combination equivalent to, but not limited to, the following:Ability to sit at a desk to perform the job functionsAbility to attend meetings at various offices as needed",
  },
  {
    company: "Deqode",
    type: "Full-Time",
    description:
      "What You’ll Do:Collaborate in every stage of a product's lifecycle; from planning to deliveryCreate clean, modern, testable, well-documented codeAgile process with CI/CD environment to develop scalable web applicationsCommunicate daily with clients to understand and deliver technical requirementsWhat is Required:7+ years professional development experience5+ years professional experience in a senior developer role with JavaPreferred: critical software development in large enterprisesExperience with Java 1.8 or laterStrong understanding of Java multithreading, concurrency and memory managementExcellent coding practices including a solid understanding of design patterns and object-oriented programmingExperience with Spring (Framework, Security, MVC, Boot)Experience building maintainable and efficient tests using tools such as MyBatis, JUnit, TestNG, Mockito etc.Coding standards to include unit, integration and acceptance testingExperience with Cloud services (AWS, Azure, OpenShift etc.)Experience with SQL and NoSQLExperience with Git/GitHubExperience with ContainersKnowledge of micro-services networking, load balancing, service discovery concepts and technologiesStrong understanding of the agile software development processSuperior communication skills in EnglishHow We WorkWhy do people join Clevertech? To make an impact. To grow themselves. To be surrounded by developers who they can learn from. We are truly excited to be creating waves in an industry under transformation.True innovation comes from an exchange of knowledge across all of our teams. To put people on the path for success, we nurture a culture built on trust, collaboration, and personal growth. You will work in small feature-based cross-functional teams and be empowered to take ownership.We make a point of constantly evolving our experience and skills. We value diverse perspectives and fostering personal growth by challenging everyone to push beyond our comfort level and try something new.The result? We produce meaningful workGetting HiredWe hire people from a variety of backgrounds who are respectful, collaborative, and introspective. Members of the tech team, for example, come from diverse backgrounds having worked as copy editors, graphic designers, and photographers prior to joining Clevertech.Our hiring process focuses not only on your skills but also on your professional and personal ambitions. We want to get to know you. We put a lot of thought into the interview process in order to get a holistic understanding of you while being mindful of your time. You will solve problems derived from the work we do on a daily basis followed by thoughtful discussions around potential fit. Whatever the outcome, we want you to have a great candidate experience.Want to learn more about Clevertech and the team? Check out clevertech.careers and our video highlighting Clevertech's Career Growth Video",
  },
  {
    company: "Deqode",
    type: "Full-Time",
    description:
      " Data Developer The successful Data Developer – will develop applications and data intensive features that inform and influence operational strategies and organizational decisions across VIN and its online communities. The ideal candidate will have a strong aptitude for SQL, NodeJS/Python and working with data. Working closely with other members of the Data team and leads across the organization, you will develop tools to process data, build complex datasets, develop applications that drive VIN. DESCRIPTION OF DUTIES Hands-on leadership, influence, and development of all things data.Develop modern data architectural approaches for business intelligence reporting and analytics, ensuring effectiveness, scalability, and reliability.Design, develop, implement, and optimize existing ETL processes that merge data from disparate sources for consumption by analysts, stakeholders, and decisions makers.Facilitate data transformation, normalization, cleansing, aggregation, workflow management, and business rule application.Detect data quality issues, identify their root causes, implement fixes, and design data audits to capture issues.Distill technical requirements into the product development and operational process via continuous collaboration with product owners, developers, and operational team members.Influence and communicate with all levels of stakeholders including analysts, developers, business users, and executives.Use analytics to influence product development, surfacing data around product usage and customer behavior.SUMMARY OF REQUIREMENTS Ability and affinity for understanding the big picture of VIN and a drive to ask and answer questions that matter to all within the organization.You are an expert in SQL You are fluent in a modern programming language Node/Python/C# (Node preferred) You are comfortable manipulating large data setsComfortable working with multiple different data storage systems ranging from NoSQL to SQLTypically, 6+ years experience in a data engineering related role (Data Warehouse Developer, ETL Developer, Business Intelligence Analytics, Software Engineer) with a track record of manipulating, processing and extracting value from datasetsStrong stakeholder interaction and influence experience at executive, business stakeholder, and engineering team levels",
  },
  {
    company: "Deqode",
    type: "Full-Time",
    description:
      "DescriptionWe are looking for a remote Android Developer to join a small, committed technical team at Ad Hoc Labs, makers of the Burner & Firewall apps. We empower people to take control over their identity and privacy by giving them fully functional, powerful, and reliable second phone numbers.As an Android Developer, you will be writing code to build new features, execute user interfaces, and help maintain and improve the current codebase. Since we are a small team, you will also have the opportunity to learn new technologies and contribute directly to the development of a product that millions of people rely on to help protect their privacy.RESPONSIBILITIES INCLUDE:Development of native Android app while working on an agile teamSupport the entire application lifecycle (concept, design, test, release and support)Write clean, maintainable native application code for AndroidEnsure app performance, quality, and responsivenessPackage apps for deployment to Google Play Store and help with automation tasksTransform designs into awesome and functional user experiencesKeep up to date knowledge of emerging Android technologiesSKILLS + QUALIFICATIONS:3+ years with Kotlin or Java and Android SDKWorked on at least one application published to the Google Play storeExperience with the various means of automated testing (junit4/5, robolectric, espresso)Experience with modern mobile software design patterns (MVP, MVI, MVVM, etc)Knowledge of popular 3rd party Android tools and apisExperience with RXJava, Kotlin Coroutines, Dagger2, AndroidX (lifecycle, workmanager, etc)Ability to diagnose problems and solve them independentlyExperience working with distributed, agile teamsExperience with Google Play Billing is a bonusWHAT WE OFFER YOU:Meaningful work on an innovative and growing set of productsCollaborative, cross-functional work culture with an emphasis on autonomy and communicationHealth and Dental coverage for employees, dependents & domestic partnersInvestment in career development, including training, conferences, and online learning resources Ad Hoc Labs is committed to building a diverse, inclusive company and encourages applications from candidates of all backgrounds. Ad Hoc Labs, Inc. is an equal employment opportunity employer and makes employment decisions on the basis of merit. We seek to employ the most qualified person in every job. Ad Hoc Labs, Inc. does not discriminate on the basis of sex, gender (including pregnancy, childbirth, breastfeeding or related medical conditions), gender identity, gender expression, age, color, race, religion, marital status, national origin, ancestry, sexual orientation, physical & mental disability, medical condition, genetic information, military and veteran status, or any other basis protected by federal, state or local law. Applicants with disabilities may be entitled to reasonable accommodation under the terms of the Americans with Disabilities Act and certain state or local laws.",
  },
];

  const technologies = [
  "Action!",
  "ActionScript",
  "Active Server Pages",
  "Ada",
  "Agilent VEE",
  "Aldor",
  "Algolia",
  "Amazon ECS",
  "AmbientTalk",
  "Amiga E",
  "Android",
  "AngelScript",
  "Angular",
  "AngularJS",
  "Apache",
  "Apache Mesos",
  "Apache Solr",
  "Apex",
  "Apisearch",
  "APL",
  "App Inventor for Android's visual block language",
  "AppleScript",
  "Argus",
  "Artificial Intelligence",
  "Assembly language",
  "AutoHotkey",
  "Automation",
  "Averest",
  "AWK",
  "AWS",
  "AWS Fargate",
  "Axum",
  "Azure",
  "Azure Search",
  "Babbage",
  "Backbone.js",
  "Backend",
  "Ballerina",
  "BASIC",
  "Batch file (Windows/MS-DOS)",
  "BeanShell",
  "Beautiful Soup",
  "Bertrand",
  "BETA",
  "Big Data",
  "Bitcoin",
  "Blockchain",
  "BlooP",
  "Bokeh",
  "Boo",
  "Boomerang",
  "Bootstrap",
  "Bourne shell (including bash and ksh)",
  "BTC",
  "C Shell (csh)",
  "C++",
  "Cach� ObjectScript",
  "Camel",
  "Caml",
  "Cappuccino",
  "Cassandra",
  "Chapel",
  "Chaplin.js",
  "Charity",
  "Charm",
  "CHILL",
  "chomski",
  "ChucK",
  "CI/CD automation",
  "Clarion",
  "Clipper",
  "CLIPS",
  "CLIST",
  "Clojure",
  "Cloud",
  "Cloud Computing",
  "CloudFlare",
  "Cloudsmash",
  "Cludo Site Search",
  "Cobra",
  "CoffeeScript",
  "ColdFusion",
  "Combined (CPL)",
  "Common Lisp (also known as CL)",
  "Constraint Handling Rules (CHR)",
  "Cool",
  "Coral 66",
  "Csound",
  "CSS",
  "Cuneiform",
  "Curl",
  "Curry",
  "Cyber Security",
  "Cyclone",
  "Cython",
  "Data Mining",
  "Data Science",
  "Database",
  "Database Management",
  "DataFlex",
  "Datalog",
  "DATATRIEVE",
  "DAX (Data Analysis Expressions)",
  "dBase",
  "DeepBrain Chain",
  "Devise",
  "DevOps",
  "Digital Marketing",
  "DinkC",
  "Django",
  "Docker",
  "DockerHub",
  "Dog",
  "Dojo Widgets",
  "Draco",
  "DYNAMO",
  "ECMAScript",
  "Eiffel",
  "Elasticlunr",
  "Elasticsearch",
  "Elixir",
  "Emacs Lisp",
  "Ember.js",
  "Epigram",
  "ESPOL",
  "Esterel",
  "ETH",
  "Ethereum",
  "Euphoria",
  "EusLisp Robot",
  "EXEC 2",
  "Executable UML",
  "Expertrec Search Engine",
  "Express.js",
  "ExpressJs",
  "Ext JS",
  "Ext JS by Sencha",
  "F-Script",
  "Fantom",
  "fish",
  "Flask",
  "Fortress",
  "Franz Lisp",
  "Frontend",
  "G-code",
  "Game Maker Language",
  "GameMonkey Script",
  "GDScript",
  "GEORGE",
  "GIT",
  "Github",
  "GLSL",
  "Go",
  "G�del",
  "Golem",
  "Golo",
  "GOM (Good Old Mad)",
  "Google Apps Script",
  "Google Closure Library",
  "Google Cloud Platform",
  "Google Kubernetes Engine",
  "Google Web Toolkit",
  "Graphene",
  "Graphic Design",
  "GraphTalk",
  "GRASS",
  "Grasshopper",
  "Groovy",
  "H2O",
  "Hack",
  "Hadoop",
  "Hadoop Stack",
  "HAGGIS",
  "HAL/S",
  "Halide (programming language)",
  "Hamilton C shell",
  "Harbour",
  "Hartmann pipelines",
  "Haskell",
  "HDFS",
  "Hermes",
  "High Level Assembly",
  "HLSL",
  "HolyC",
  "IBM Basic assembly language",
  "Hop",
  "Hope",
  "Hopscotch",
  "HTML",
  "Hugo",
  "Hyperledger",
  "HyperTalk",
  "IBM HAScript",
  "IBM Informix-4GL",
  "IBM RPG",
  "JADE",
  "Jasmine",
  "JASS",
  "Java",
  "JavaFX Script",
  "JavaScript",
  "JavaScriptMVC",
  "JCL",
  "JEAN",
  "Jenkins",
  "Jess (programming language)",
  "JIRA",
  "Join Java",
  "Joule",
  "JOVIAL",
  "Joy",
  "JQuery",
  "jQuery UI",
  "jQWidgets",
  "js",
  "JScript",
  "JScript .NET",
  "JsPHP",
  "JsRender/JsViews",
  "Julia",
  "Jython",
  "Kafka",
  "Kaleidoscope",
  "Karel",
  "Klerer-May System",
  "Knockout",
  "KoaJS",
  "Kodu",
  "Kojo",
  "Korn shell (ksh)",
  "KRL (KUKA Robot Language)",
  "KRYPTON",
  "Kubernetes",
  "Legoscript",
  "LetsTalkServers",
  "Librosa",
  "LilyPond",
  "Limbo",
  "Lime",
  "Lingo",
  "Lite-C",
  "Lithe",
  "Little b",
  "LiveCode",
  "LiveScript",
  "Logtalk",
  "LotusScript",
  "Machine code",
  "Madmom",
  "Magma",
  "MATH-MATIC",
  "Mathcad",
  "Mathematica",
  "MATLAB",
  "Matplotlib",
  "Maxima (see also Macsyma)",
  "MaxScript internal language 3D Studio Max",
  "Mercury",
  "Meteor",
  "Microcode",
  "MicroScript",
  "Microsoft Azure",
  "Microsoft's Ajax library",
  "Milk (programming language)",
  "Miranda",
  "MIVA Script",
  "ML",
  "Mobile",
  "Mobile Applications",
  "Mocha",
  "MochiKit",
  "Model 204",
  "Modelica",
  "Modula",
  "Mohol",
  "Mojito",
  "Mongo",
  "Mongodb",
  "MOO",
  "MooTools",
  "Mouse",
  "MUMPS",
  "MuPAD",
  "MySQL",
  "Mystic (MPL)",
  "NASM",
  "Neko",
  "Neo4j",
  "NestJs",
  "Net.Data",
  "NetLogo",
  "NewLISP",
  "Newspeak",
  "NewtonScript",
  "Next Generation Shell",
  "Nial",
  "Nice",
  "Nickle (NITIN)",
  "Nim",
  "Node.js",
  "NodeJS",
  "NoSQL",
  "Not eXactly C (NXC)",
  "Not Quite C (NQC)",
  "NPL",
  "NSIS",
  "NumPy",
  "NWScript",
  "NXT-G",
  "o:XML",
  "Oak",
  "Oberon",
  "OBJ2",
  "Object Lisp",
  "Object Pascal",
  "Object REXX",
  "Objective-C",
  "Objective-J",
  "ObjectiveC",
  "ObjectLOGO",
  "Obliq",
  "Octave",
  "OmniMark",
  "Opa",
  "Opal",
  "Open Source Technology Integration",
  "OpenCL",
  "OpenCV-Python",
  "OpenEdge ABL",
  "OpenSearchServer",
  "OpenUI5 by SAP",
  "OpenVera",
  "Operating Systems",
  "OPS5",
  "Optimizing Website Performance",
  "OptimJ",
  "Oracle",
  "Orc",
  "ORCA/Modula-2",
  "Oxygene",
  "Pandas",
  "ParaSail",
  "Pascal Script",
  "PassportJs",
  "PDF.js",
  "PeopleCode",
  "Perl",
  "Pharo",
  "PHP",
  "Pico",
  "Picolisp",
  "Pig (programming tool)",
  "Pillow",
  "Pinecone",
  "Pipelines",
  "Planner",
  "PLEX",
  "PLEXIL",
  "Plus",
  "Polymer (library) by Google",
  "PortablE",
  "Portainer",
  "Postgres",
  "PostgreSQL",
  "PostScript",
  "Powerhouse",
  "PowerShell",
  "Processing",
  "Processing.js",
  "Prograph",
  "Prolog",
  "PROMAL",
  "Promela",
  "PROSE modeling language",
  "Prototype JavaScript Framework",
  "ProvideX",
  "Psycopg",
  "PureMVC",
  "PureScript",
  "pyAudioAnalysis",
  "PyOD",
  "Python",
  "PyTorch",
  "Q (programming language from Kx Systems)",
  "Q# (Microsoft)",
  "Qalb",
  "Qbasic",
  "QtScript",
  "QuakeC",
  "QUnit",
  "Racket",
  "Rails",
  "Raku",
  "RAPID",
  "Rapira",
  "Ratfiv",
  "Ratfor",
  "RDS",
  "React",
  "React.js",
  "ReactNative",
  "REBOL",
  "Redcode",
  "Redis",
  "Rialto Toolkit",
  "Rico",
  "Ripple",
  "Rlab",
  "RPL",
  "Ruby",
  "Rust",
  "S-Lang",
  "S-PLUS",
  "SaaS",
  "SabreTalk",
  "Sawtooth",
  "Scala",
  "Scikit-image",
  "Scikit-learn",
  "Scilab",
  "Scrapy",
  "Scratch",
  "Script.NET",
  "Seaborn",
  "Search Engine Optimization",
  "SearchTap.io",
  "SearchUnit",
  "Seed7",
  "Selenium",
  "Self",
  "SenseTalk",
  "SEO",
  "SequenceL",
  "Simula",
  "Sinatra (Ruby)",
  "Singularity",
  "Smalltalk",
  "SmartClient",
  "Snowball",
  "Socket.IO",
  "Solidity",
  "Solr",
  "SP/k",
  "Spacy",
  "SPARK",
  "Speakeasy",
  "Speedcode",
  "Sphinx",
  "SproutCore",
  "Spry framework",
  "SPS",
  "SQL",
  "SQLAlchemy",
  "SQLite",
  "Squirrel",
  "Stata",
  "Stateflow",
  "Storm",
  "Strongtalk",
  "SuperCollider",
  "SuperTalk",
  "Swift",
  "Swift (Apple)",
  "Swift (parallel scripting language)",
  "SYMPL",
  "System Reboot",
  "SystemVerilog",
  "T-SQL",
  "TACL",
  "Tcl",
  "Tea",
  "Teamwork",
  "TECO",
  "TensorFlow",
  "Tomcat",
  "Transcript",
  "Turing",
  "TUTOR",
  "Tynker",
  "TypeScript",
  "Ubercode",
  "UCSD Pascal",
  "Umple",
  "Underscore.js",
  "Unix shell",
  "UnrealScript",
  "UX Design",
  "Velocity experience (HUGE PLUS)",
  "Vim script",
  "Visual Basic",
  "Visual Basic .NET",
  "Visual DataFlex",
  "Visual DialogScript",
  "Visual Fortran",
  "Visual FoxPro",
  "Visual J++",
  "Visual Objects",
  "Visual Prolog",
  "VPC",
  "VSXu",
  "Vue",
  "Vue.js",
  "VueJs",
  "Wakanda Framework",
  "Watson",
  "Web Application",
  "WebAssembly",
  "WebDNA",
  "Webix",
  "Whiley",
  "Whoosh",
  "Winbatch",
  "WinJS",
  "Wolfram Language",
  "Wordpress",
  "WordPress Plugin Design",
  "Wyvern",
  "Xapian",
  "xBase",
  "xBase++",
  "XBL",
  "XC (targets XMOS architecture)",
  "xHarbour",
  "Xojo",
  "XOTcl",
  "XPath",
  "XQuery",
  "XSharp",
  "Z notation",
  "Z++",
  "Zebra, ZPL, ZPL2",
  "Zsh",
  "ROR",
  "CSharp",
  "VBA",
];

module.exports={jobs,technologies}